service: clock-inout-api

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  timeout: 30
  stage: dev
  region: ap-northeast-1
  environment:
    USERID: ${self:custom.env.USERID}
    PASSWORD: ${self:custom.env.PASSWORD}

functions:
  # hello:
  #   handler: handler.hello
  #   layers:
  #     - { Ref: ChromiumLambdaLayer }
  clockin:
    handler: handler.clockin
    events:
      - http:
          method: post
          path: clockin
    layers:
      - { Ref: ChromiumLambdaLayer }
  clockout:
    handler: handler.clockout
    events:
      - http:
          method: post
          path: clockout
    layers:
      - { Ref: ChromiumLambdaLayer }

layers:
  chromium:
    path: chromium

custom:
  webpack:
    includeModules:
      forceExclude:
        - chrome-aws-lambda
        - puppeteer-core
  env: ${file(env.yml)}
